### ISSUE TITLE
Re-running the enable_hstore recipe raises an error.

### ISSUE THREAD

**Issue by cmaxw** [chef-ubuntu/postgresql#1]
==> default:
==> default: ================================================================================
==> default: Error executing action `run` on resource 'bash[enable hstore]'
==> default: ================================================================================
==> default:
==> default:
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '1'
==> default:
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150115-1563-1hljfxq" ----
==> default:
==> default: STDOUT:
==> default:
==> default: STDERR: ERROR:  extension "hstore" already exists
==> default:
==> default: ---- End output of "bash"  "/tmp/chef-script20150115-1563-1hljfxq" ----
==> default:
==> default: Ran "bash"  "/tmp/chef-script20150115-1563-1hljfxq" returned 1
==> default:
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/postgresql/recipes/enable_hstore.rb
==> default:
==> default:   3: bash "enable hstore" do
==> default:   4:   code <<-EOF
==> default:   5:     psql template1 -c 'create extension hstore;'
==> default:   6:   EOF
==> default:   7:   user "postgres"
==> default:   8:   not_if "test -e #{lock}"
==> default:   9: end
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/postgresql/recipes/enable_hstore.rb:3:in `from_file'
==> default:
==> default: bash("enable hstore") do
==> default:   action "run"
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   command "\"bash\"  \"/tmp/chef-script20150115-1563-1hljfxq\""
==> default:   backup 5
==> default:   returns 0
==> default:   user "postgres"
==> default:   code "    psql template1 -c 'create extension hstore;' \n"
==> default:   interpreter "bash"
==> default:   declared_type :bash
==> default:   cookbook_name :postgresql
==> default:   recipe_name "enable_hstore"
==> default:   not_if "test -e /var/chef/cache/postgresql_enable_hstore_lock"
==> default: end
==> default:
==> default: [2015-01-15T20:50:55+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-01-15T20:50:55+00:00] ERROR: Running exception handlers
==> default: [2015-01-15T20:50:55+00:00] ERROR: Exception handlers complete
==> default: [2015-01-15T20:50:55+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-01-15T20:50:55+00:00] ERROR: bash[enable hstore] (postgresql::enable_hstore line 3) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150115-1563-1hljfxq" ----
==> default: STDOUT:
==> default: STDERR: ERROR:  extension "hstore" already exists
==> default: ---- End output of "bash"  "/tmp/chef-script20150115-1563-1hljfxq" ----
==> default: Ran "bash"  "/tmp/chef-script20150115-1563-1hljfxq" returned 1
==> default: [2015-01-15T20:50:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by ryanburnette** [comment]
What's weird about that is that there's a lockfile which prevents it from being run multiple times. If `hstore` is already configured when the recipe is run for the first time it could be a problem though. I probably need to test to see if `hstore` is turned on in the bash script.

**Comment by ryanburnette** [comment]
I added -q to the `psql` command. It's okay for this to be run repeatedly so this might fix it. I'll post again when I test it.

**Comment by ryanburnette** [comment]
If needed I could write a bash test in the checks if `hstore` is enabled. I got some [advice on SO][1] about it.

[1]: http://stackoverflow.com/a/27972909/2535178

**Comment by ryanburnette** [comment]
@cmaxw This is fixed for sure now.
